export const luluColors = [
  "Lulu Indigo",
  "Lulu Indigo Dark",
  "Lulu Indigo Light",
  "Lulu Indigo Bkgd",
  "Lulu Cyan",
  "Lulu Cyan Dark",
  "Lulu Cyan Light",
  "Lulu Cyan Bkgd",
  "Lulu Magenta",
  "Lulu Magenta Dark",
  "Lulu Magenta Light",
  "Lulu Magenta Bkgd",
  "Lulu Yellow",
  "Lulu Yellow Dark",
  "Lulu Yellow Light",
  "Lulu Yellow Bkgd",
  "Lulu Green",
  "Lulu Green Dark",
  "Lulu Green Light",
  "Lulu Green Bkgd",
  "Lulu Orange",
  "Lulu Orange Dark",
  "Lulu Orange Light",
  "Lulu Orange Bkgd",
  "Lulu Red",
  "Lulu Red Dark",
  "Lulu Red Light",
  "Lulu Red Bkgd",
  "Lulu Purple",
  "Lulu Purple Dark",
  "Lulu Purple Light",
  "Lulu Purple Bkgd",
  "Lulu Ocean",
  "Lulu Ocean Dark",
  "Lulu Ocean Light",
  "Lulu Teal",
  "Lulu Teal Dark",
  "Lulu Teal Light",
  "Lulu Lime",
  "Lulu Lime Dark",
  "Lulu Lime Light",
  "Lulu Tangerine",
  "Lulu Tangerine Dark",
  "Lulu Tangerine Light",
  "Lulu Linen Red",
  "Lulu Linen Navy",
  "Lulu Linen Black",
  "Lulu Linen Gray",
  "Lulu Linen Tan",
  "Lulu Linen Forest",
  "Lulu Foil Black",
  "Lulu Foil White",
  "Lulu Foil Gold",
  "Lulu Dark Gray 1",
  "Lulu Dark Gray 2",
  "Lulu Dark Gray 3",
  "Lulu Dark Gray 4",
  "Lulu Dark Gray 5",
  "Lulu Dark Gray 6",
  "Lulu Pale Gray 1",
  "Lulu Pale Gray 2",
  "Lulu Pale Gray 3",
  "Lulu Pale Gray 4",
  "Lulu Pale Gray 5",
  "Lulu Pale Gray 6",
  "Lulu Almost Black",
  "Lulu Almost Black 90%",
  "Lulu Almost Black 80%",
  "Lulu Almost Black 70%",
  "Lulu Almost Black 60%",
  "Lulu Almost Black 10%",
  "White",
  "White 90%",
  "White 80%",
  "White 70%",
  "White 60%",
  "White 50%",
  "Lulu Gradient: Indigo - Cyan",
  "Lulu Gradient: Cyan - Purple",
  "Lulu Gradient: Cyan - Magenta",
  "Lulu Gradient: Cyan - Lime",
  "Lulu Gradient: Classic 1",
  "Lulu Gradient: Classic 2",
  "Lulu Gradient: Classic 3",
  "Lulu Gradient: Classic 4",
  "Lulu Gradient: Lulu Background 1",
  "Lulu Gradient: Lulu Background 2",
  "Lulu Gradient: Lulu Direct Background",
  "Lulu Gradient: Lulu API Background",
  "Lulu Gradient: Lulu Logo",
  "Lulu Gradient: Lulu Direct Logo",
  "Lulu Gradient: Lulu API Logo",
];

const mapLuluColors: Record<string, string> = {
  "#000083": "Lulu Indigo",
  "#00004F": "Lulu Indigo Dark",
  "#2424B5": "Lulu Indigo Light",
  "#E5E5F2": "Lulu Indigo Bkgd",
  "#22B5F0": "Lulu Cyan",
  "#099CD6": "Lulu Cyan Dark",
  "#3DC8FF": "Lulu Cyan Light",
  "#E8F7FD": "Lulu Cyan Bkgd",
  "#A41CAD": "Lulu Magenta",
  "#8B0994": "Lulu Magenta Dark",
  "#BD34C7": "Lulu Magenta Light",
  "#F6E8F7": "Lulu Magenta Bkgd",
  "#FFE600": "Lulu Yellow",
  "#FFD908": "Lulu Yellow Dark",
  "#FFF238": "Lulu Yellow Light",
  "#FFFCE5": "Lulu Yellow Bkgd",
  "#00A873": "Lulu Green",
  "#008F62": "Lulu Green Dark",
  "#13C28B": "Lulu Green Light",
  "#F2FAF8": "Lulu Green Bkgd",
  "#FF7500": "Lulu Orange",
  "#F05400": "Lulu Orange Dark",
  "#FF8F0A": "Lulu Orange Light",
  "#FFF8F2": "Lulu Orange Bkgd",
  "#D6223A": "Lulu Red",
  "#BD0B23": "Lulu Red Dark",
  "#F03E56": "Lulu Red Light",
  "#FDF3F5": "Lulu Red Bkgd",
  "#6313BD": "Lulu Purple",
  "#4A009E": "Lulu Purple Dark",
  "#8030DB": "Lulu Purple Light",
  "#F7F3FB": "Lulu Purple Bkgd",
  "#086ACC": "Lulu Ocean",
  "#0059B3": "Lulu Ocean Dark",
  "#2083E6": "Lulu Ocean Light",
  "#00869E": "Lulu Teal",
  "#007185": "Lulu Teal Dark",
  "#129FB8": "Lulu Teal Light",
  "#94D232": "Lulu Lime",
  "#81BF1D": "Lulu Lime Dark",
  "#A7E346": "Lulu Lime Light",
  "#FFA505": "Lulu Tangerine",
  "#FA9100": "Lulu Tangerine Dark",
  "#FFC038": "Lulu Tangerine Light",
  "#993030": "Lulu Linen Red",
  "#2B3550": "Lulu Linen Navy",
  "#232327": "Lulu Linen Black",
  "#505354": "Lulu Linen Gray",
  "#958E7F": "Lulu Linen Tan",
  "#445F4D": "Lulu Linen Forest",
  "#000000": "Lulu Foil Black",
  "#9D7710": "Lulu Foil Gold",
  "#8D97A8": "Lulu Dark Gray 1",
  "#F3F4F9": "Lulu Dark Gray 1",
  "#717C8F": "Lulu Dark Gray 2",
  "#525F75": "Lulu Dark Gray 3",
  "#37455C": "Lulu Dark Gray 4",
  "#25334D": "Lulu Dark Gray 5",
  "#18263D": "Lulu Dark Gray 6",
  "#F2F4FA": "Lulu Pale Gray 1",
  "#E9EDF6": "Lulu Pale Gray 2",
  "#DCE0EB": "Lulu Pale Gray 3",
  "#D1D6E0": "Lulu Pale Gray 4",
  "#C0C6D1": "Lulu Pale Gray 5",
  "#AEB6C2": "Lulu Pale Gray 6",
  "#0A101A": "Lulu Almost Black",
  "#232831": "Lulu Almost Black 90%",
  "#3B4048": "Lulu Almost Black 80%",
  "#54585F": "Lulu Almost Black 70%",
  "#6C7076": "Lulu Almost Black 60%",
  "#E7E8E9": "Lulu Almost Black 10%",
  "#FFFFFF": "White",
  "#E5E5E5": "White 90%",
  "#CCCCCC": "White 80%",
  "#B2B2B2": "White 70%",
  "#999999": "White 60%",
  "#808080": "White 50%",
};

export const transformEntryForColorFields = (fields: string[]) => {
  return (from: any, _locale: any) => {
    let transformations = {};
    for (const field of fields) {
      if (from?.[field] !== undefined) {
        transformations = {
          ...transformations,
          [field]:
            mapLuluColors?.[from[field]["en-US"]?.toUpperCase()] ??
            "Lulu Almost Black",
        };
      }
    }

    return transformations;
  };
};
